-- =============================================================================
-- Modèle : dimension historisée SCD type 2 (PostgreSQL)
-- Convention : docs/database/02_ARCHITECTURE_LAYERS.md §4.2 et §5
--
-- Remplacer :
--   <domain>  schéma de domaine (finance, hr…) ou "dwh" si la dimension est partagée
--   <entity>  entité au singulier, en anglais (customer, employee…)
-- =============================================================================

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS <domain>.dim_<entity> (
    -- Clé de substitution (générée par l'entrepôt)
    <entity>_key        BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Clé naturelle (source)
    <entity>_id         BIGINT        NOT NULL,

    -- Attributs descriptifs (libellés lisibles, hiérarchies aplaties)
    <entity>_code       VARCHAR(30)   NOT NULL,
    <entity>_name       VARCHAR(255)  NOT NULL,
    status_code         VARCHAR(30)   NOT NULL,
    status_label        VARCHAR(100)  NOT NULL,
    country_code        CHAR(2),
    country_name        VARCHAR(100),

    -- Historisation SCD 2 : intervalle semi-ouvert [valid_from, valid_to)
    valid_from          TIMESTAMPTZ   NOT NULL,
    valid_to            TIMESTAMPTZ,
    is_current          BOOLEAN       NOT NULL DEFAULT true,
    row_hash            CHAR(64)      NOT NULL,

    -- Colonnes techniques
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    loaded_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    batch_id            VARCHAR(250)  NOT NULL,

    CONSTRAINT pk_dim_<entity> PRIMARY KEY (<entity>_key),
    CONSTRAINT ck_dim_<entity>_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);

-- Une seule version courante par clé naturelle
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_<entity>_current
    ON <domain>.dim_<entity> (<entity>_id)
    WHERE is_current;

-- Recherche d'une version à une date donnée
CREATE INDEX IF NOT EXISTS ix_dim_<entity>_id_valid_from
    ON <domain>.dim_<entity> (<entity>_id, valid_from);

-- Membres spéciaux : -1 = inconnu, -2 = non applicable
INSERT INTO <domain>.dim_<entity> (
    <entity>_key, <entity>_id, <entity>_code, <entity>_name,
    status_code, status_label, valid_from, row_hash, batch_id
)
OVERRIDING SYSTEM VALUE
VALUES
    (-1, -1, 'UNKNOWN', 'Unknown',        'UNKNOWN', 'Unknown',        '1900-01-01', repeat('0', 64), 'init'),
    (-2, -2, 'N/A',     'Not applicable', 'N/A',     'Not applicable', '1900-01-01', repeat('0', 64), 'init')
ON CONFLICT (<entity>_key) DO NOTHING;

COMMENT ON TABLE <domain>.dim_<entity> IS
    'Dimension <entity> historisée (SCD 2). Grain : 1 ligne par version de <entity>.';
COMMENT ON COLUMN <domain>.dim_<entity>.valid_to IS
    'Fin de validité exclue ; NULL pour la version courante';
